import React, { useState } from 'react';
import {
  FileText,
  Download,
  Trash2,
  Search,
  Filter,
  ArrowUpRight,
  Database,
  ExternalLink,
  History,
  AlertTriangle
} from 'lucide-react';
import { GlassCard, NeonButton, Modal } from '../components/UI/UIComponents';
import { useSimulationStore } from '../store/simulationStore';

const ReportsView = () => {
  const {
    simulationHistory: reports,
    clearHistory,
    deleteReport
  } = useSimulationStore();

  const [showClearModal, setShowClearModal] = useState(false);

  const confirmClear = () => {
    clearHistory();
    setShowClearModal(false);
  };

  const handleDelete = (id) => {
    deleteReport(id);
  };

  // Calculate dynamic stats from the reports array
  const totalSims = reports.length;
  const avgWait = reports.length > 0
    ? (reports.reduce((acc, curr) => acc + curr.wait, 0) / reports.length).toFixed(1)
    : '0.0';

  // Find top algorithm
  const algoCounts = reports.reduce((acc, curr) => {
    acc[curr.algo] = (acc[curr.algo] || 0) + 1;
    return acc;
  }, {});
  const topAlgo = reports.length > 0
    ? Object.entries(algoCounts).reduce((a, b) => a[1] > b[1] ? a : b)[0]
    : 'None';

  const stats = [
    { label: 'Total Simulations', val: totalSims.toString(), icon: Database, color: 'text-primary', bg: 'bg-primary/5' },
    { label: 'Avg System Wait', val: `${avgWait}ms`, icon: FileText, color: 'text-secondary', bg: 'bg-secondary/5' },
    { label: 'Top Algorithm', val: topAlgo, icon: Filter, color: 'text-emerald-500', bg: 'bg-emerald-500/5' },
    { label: 'Reports Exported', val: reports.length > 0 ? '42' : '0', icon: Download, color: 'text-amber-500', bg: 'bg-amber-500/5' },
  ];

  const downloadReport = (report) => {
    const filename = `KernelFlow_Report_${report.id}.txt`;
    const content = `
KERNELFLOW SIMULATION REPORT
====================================
ID:         ${report.id}
Timestamp:  ${report.date} ${report.time}
Algorithm:  ${report.algo}
------------------------------------
METRICS:
Average Waiting Time:    ${report.wait} ms
Average Turnaround Time: ${report.tat} ms
Average CPU Load:        ${report.util} %
Throughput:              ${report.completed || 0} / ${report.total_time || 0} proc/ms
====================================
Generated by KernelFlow OS Simulator
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
  };

  const exportAll = () => {
    if (reports.length === 0) return;
    const filename = `KernelFlow_Full_Archive.txt`;
    let content = `KERNELFLOW FULL ARCHIVE EXPORT\n`;
    content += `Generated on: ${new Date().toLocaleString()}\n`;
    content += `====================================\n\n`;

    reports.forEach(r => {
      content += `[${r.id}] ${r.algo} | Wait: ${r.wait}ms | TAT: ${r.tat}ms | Load: ${r.util}% | Throughput: ${r.completed || 0}/${r.total_time || 0} proc/ms\n`;
    });

    content += `\n====================================\n`;
    content += `End of Archive`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-12 animate-slide-in max-w-6xl mx-auto py-10">
      <div className="flex items-center justify-between">
        <div className="flex flex-col gap-3">
          <h1 className="text-4xl font-black text-white italic uppercase tracking-tighter">
            Archive <span className="text-primary">Database</span>
          </h1>
          <p className="text-slate-500 text-sm font-medium tracking-wide">Historical simulation records and exported performance telemetry.</p>
        </div>
        <div className="flex items-center gap-4">
          <NeonButton
            icon={Trash2}
            variant="ghost"
            onClick={() => setShowClearModal(true)}
            className="text-accent-rose hover:bg-accent-rose/10 border-accent-rose/20"
          >
            Clear Archive
          </NeonButton>
          <NeonButton
            icon={Download}
            variant="secondary"
            onClick={exportAll}
            disabled={reports.length === 0}
          >
            Export All Data
          </NeonButton>
        </div>
      </div>

      <div className="grid grid-cols-12 gap-8">
        {/* Stats Summary */}
        <div className="col-span-12 grid grid-cols-4 gap-8">
          {stats.map((s, i) => (
            <GlassCard key={i} noPad className="flex flex-col gap-6 p-8 transition-all hover:scale-[1.02] border-white/5">
              <div className={`w-14 h-14 rounded-2xl ${s.bg} border border-white/5 flex items-center justify-center ${s.color} shadow-inner`}>
                <s.icon size={28} strokeWidth={2} />
              </div>
              <div className="space-y-2">
                <p className="text-[10px] font-black text-slate-500 uppercase tracking-[0.25em]">{s.label}</p>
                <p className="text-4xl font-black text-white tracking-tighter italic uppercase">{s.val}</p>
              </div>
            </GlassCard>
          ))}
        </div>

        {/* Reports Table */}
        <GlassCard
          className="col-span-12"
          title="Recent Activity"
          subtitle="Simulation Log Archive"
          icon={History}
          actions={
            <div className="flex items-center gap-2">
              <div className="relative">
                <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" />
                <input
                  type="text"
                  placeholder="Search IDs..."
                  className="pl-9 pr-4 py-2 rounded-xl bg-dark-800 border-dark-600 text-xs text-white outline-none focus:ring-1 focus:ring-primary/50"
                />
              </div>
            </div>
          }
        >
          <div className="overflow-hidden">
            <table className="w-full text-left border-separate border-spacing-y-3">
              <thead>
                <tr className="text-[10px] font-black text-slate-500 uppercase tracking-widest">
                  <th className="px-6 py-2">Simulation ID</th>
                  <th className="px-6 py-2">Timestamp</th>
                  <th className="px-6 py-2">Algorithm</th>
                  <th className="px-6 py-2">Avg Wait</th>
                  <th className="px-6 py-2">Avg TAT</th>
                  <th className="px-6 py-2">CPU Load</th>
                  <th className="px-6 py-2 text-right">Actions</th>
                </tr>
              </thead>
              <tbody>
                {reports.map((r) => (
                  <tr key={r.id} className="group bg-dark-800/40 hover:bg-dark-700/60 transition-all rounded-2xl">
                    <td className="px-6 py-4 rounded-l-2xl font-black text-primary text-xs uppercase tracking-wider">{r.id}</td>
                    <td className="px-6 py-4">
                      <div className="flex flex-col">
                        <span className="text-xs font-bold text-white">{r.date}</span>
                        <span className="text-[10px] text-slate-500 font-mono">{r.time}</span>
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <span className="px-2 py-1 rounded-md bg-secondary/10 border border-secondary/20 text-[10px] font-black text-secondary uppercase italic">
                        {r.algo}
                      </span>
                    </td>
                    <td className="px-6 py-4 font-mono font-bold text-xs text-white">{r.wait}ms</td>
                    <td className="px-6 py-4 font-mono font-bold text-xs text-white">{r.tat}ms</td>
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-2">
                        <div className="w-12 h-1.5 bg-dark-600 rounded-full overflow-hidden">
                          <div className="h-full bg-emerald-500" style={{ width: `${r.util}%` }} />
                        </div>
                        <span className="text-[10px] font-bold text-emerald-500">{r.util}%</span>
                      </div>
                    </td>
                    <td className="px-6 py-4 rounded-r-2xl text-right">
                      <div className="flex justify-end gap-2">
                        <button
                          onClick={() => downloadReport(r)}
                          title="Download Text Report"
                          className="p-2 rounded-lg bg-dark-900 text-slate-400 hover:text-primary transition-colors border border-dark-600"
                        >
                          <Download size={14} />
                        </button>
                        <button
                          onClick={() => handleDelete(r.id)}
                          title="Delete Record"
                          className="p-2 rounded-lg bg-dark-900 text-slate-400 hover:text-accent-rose transition-colors border border-dark-600"
                        >
                          <Trash2 size={14} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
                {reports.length === 0 && (
                  <tr>
                    <td colSpan={7} className="py-20 text-center">
                      <div className="flex flex-col items-center gap-4 opacity-40">
                        <Database size={48} />
                        <p className="text-sm font-black uppercase tracking-widest italic">No historical data found</p>
                      </div>
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </GlassCard>
      </div>

      {/* Clear Archive Modal */}
      <Modal
        isOpen={showClearModal}
        onClose={() => setShowClearModal(false)}
        title="Wipe Simulation Archive?"
        icon={AlertTriangle}
        accent="orange"
      >
        <div className="space-y-4">
          <p>
            You are about to permanently delete all historical simulation records.
            This action cannot be undone and all performance telemetry will be lost.
          </p>
          <div className="flex gap-4 mt-6">
            <NeonButton
              variant="reset"
              className="flex-1 py-4"
              onClick={confirmClear}
            >
              Wipe Database
            </NeonButton>
            <NeonButton
              variant="ghost"
              className="flex-1 py-4"
              onClick={() => setShowClearModal(false)}
            >
              Cancel
            </NeonButton>
          </div>
        </div>
      </Modal>
    </div>
  );
};

export default ReportsView;
